// ── Cross-Feature Workflows ─────────────────────────────────────────────────
// When something happens in one feature, react in another. These chains turn
// the app from "28 disconnected pages" into a system where features amplify
// each other.
//
// Each chain is:
//   • idempotent (safe to call repeatedly; uses metadata containment to skip
//     work that's already been done)
//   • fail-soft (errors are logged, never thrown back to the caller — a
//     side-effect chain should never break the user's primary action)
//   • additive (creates entities; never updates or deletes the source)
//
// Convention: every entity created by a workflow stamps its `metadata` jsonb
// column with `{ source: '<workflow_name>', '<source>_id': '<uuid>' }`.
// Re-runs query metadata @> ... to skip duplicates.
//
// Required schema: tasks.metadata, rfis.metadata, incidents.metadata
// (all jsonb DEFAULT '{}'). See migration 20260428100000_cross_feature_metadata.sql.

/* eslint-disable @typescript-eslint/no-explicit-any */
import { supabase } from './supabase';

// The Supabase generated types lag behind the live schema for newly-added
// columns (e.g. `metadata` jsonb on tasks/rfis/incidents — added in
// 20260428100000_cross_feature_metadata.sql but not yet regenerated into
// types/database.ts). Returning `any` from this helper sidesteps the deep
// keyof-union noise; the actual schema validation happens server-side.
const from = (table: string): any => (supabase as any).from(table);

export interface WorkflowResult {
  workflow: string;
  created?: { type: 'task' | 'rfi' | 'incident' | 'change_order' | 'activity'; id: string };
  skipped?: { reason: string };
  error?: string;
}

// ── L2#1: RFI overdue → auto-create follow-up task ─────────────────────────
//
// Fires from: dashboard mount, RFIs page mount, scheduled cron (when added).
// Detects: any open or under-review RFI past its due_date by ≥ 3 days that
// doesn't already have a follow-up task. Creates a task assigned to the
// ball-in-court user, due 3 days from now, priority high.
//
// Why ball_in_court instead of assigned_to: ball_in_court is the *current*
// holder of the action. assigned_to is the original recipient. They diverge
// once the RFI is in review. Following up the BIC is what construction PMs
// actually do.

export async function runRfiOverdueSweep(projectId: string): Promise<WorkflowResult[]> {
  const results: WorkflowResult[] = [];
  try {
    const threshold = new Date();
    threshold.setDate(threshold.getDate() - 3);
    const thresholdIso = threshold.toISOString().slice(0, 10);

    const { data: overdueRfis, error: fetchError } = await from('rfis')
      .select('id, title, ball_in_court, assigned_to, due_date, priority')
      .eq('project_id', projectId)
      .in('status', ['open', 'under_review'])
      .lt('due_date', thresholdIso);

    if (fetchError) {
      results.push({ workflow: 'rfi_overdue_sweep', error: fetchError.message });
      return results;
    }
    if (!overdueRfis || overdueRfis.length === 0) return results;

    // Find which of these already have a follow-up task. We use the
    // metadata.source containment filter (which works reliably across
    // supabase-js + PostgREST) instead of `.in('metadata->>rfi_id', ids)`
    // (whose JSON-operator-in-column syntax is fragile in supabase-js).
    // Volume is bounded by total sweep-created tasks for this project,
    // typically tens at most.
    const { data: existingTasks } = await from('tasks')
      .select('metadata')
      .eq('project_id', projectId)
      .contains('metadata', { source: 'rfi_overdue_sweep' });
    const linkedRfiIds = new Set(
      ((existingTasks ?? []) as any[])
        .map((t: any) => (t?.metadata as { rfi_id?: string } | null)?.rfi_id)
        .filter((v: string | undefined): v is string => !!v),
    );

    const dueDate = new Date();
    dueDate.setDate(dueDate.getDate() + 3);
    const dueDateIso = dueDate.toISOString().slice(0, 10);

    for (const rfi of overdueRfis) {
      if (linkedRfiIds.has(rfi.id)) {
        results.push({ workflow: 'rfi_overdue_sweep', skipped: { reason: `task already exists for rfi ${rfi.id}` } });
        continue;
      }
      const assignee = (rfi as { ball_in_court?: string; assigned_to?: string }).ball_in_court
        ?? (rfi as { assigned_to?: string }).assigned_to
        ?? null;
      const daysPastDue = Math.max(
        1,
        Math.floor((Date.now() - new Date(rfi.due_date as string).getTime()) / 86_400_000),
      );

      const { data: insertedTask, error: insertError } = await from('tasks')
        .insert({
          project_id: projectId,
          title: `Follow up: overdue RFI — ${rfi.title}`,
          description:
            `RFI is ${daysPastDue} days past due. Original due date: ${rfi.due_date}. ` +
            `Auto-generated by RFI follow-up sweep.`,
          status: 'todo',
          priority: 'high',
          assigned_to: assignee,
          due_date: dueDateIso,
          metadata: { source: 'rfi_overdue_sweep', rfi_id: rfi.id },
        } as unknown as Record<string, unknown>)
        .select('id')
        .single();

      if (insertError) {
        results.push({ workflow: 'rfi_overdue_sweep', error: insertError.message });
        continue;
      }
      if (insertedTask) {
        results.push({
          workflow: 'rfi_overdue_sweep',
          created: { type: 'task', id: insertedTask.id as string },
        });
      }
    }
    return results;
  } catch (err) {
    results.push({ workflow: 'rfi_overdue_sweep', error: (err as Error).message });
    return results;
  }
}

// ── L2#2: Submittal rejected → AI-draft RFI ────────────────────────────────
//
// Fires from: submittalService.transitionStatus when newStatus === 'rejected'.
// Pulls the rejection comment + spec section + product info, calls the
// ai-rfi-draft edge function, inserts a draft RFI to the architect.
// Idempotent via rfis.metadata.submittal_id.

export async function runSubmittalRejectedChain(submittalId: string): Promise<WorkflowResult> {
  try {
    const { data: submittal, error: fetchError } = await from('submittals')
      .select('id, project_id, title, spec_section, subcontractor, created_by')
      .eq('id', submittalId)
      .maybeSingle();
    if (fetchError) return { workflow: 'submittal_rejected', error: fetchError.message };
    if (!submittal) return { workflow: 'submittal_rejected', error: 'submittal not found' };

    // Skip if a follow-up RFI already exists for this submittal.
    // jsonb containment (`@>`) is the reliable way to query this through
    // supabase-js's `.contains()` helper.
    const { data: existing } = await from('rfis')
      .select('id')
      .eq('project_id', submittal.project_id as string)
      .contains('metadata', { submittal_id: submittalId })
      .maybeSingle();
    if (existing) {
      return { workflow: 'submittal_rejected', skipped: { reason: `rfi already exists for submittal ${submittalId}` } };
    }

    // Pull the most recent rejection comment from submittal_approvals.
    const { data: rejection } = await from('submittal_approvals')
      .select('comments, role, reviewed_at')
      .eq('submittal_id', submittalId)
      .eq('status', 'rejected')
      .order('reviewed_at', { ascending: false })
      .limit(1)
      .maybeSingle();

    const rejectionContext = rejection
      ? `Rejection by ${rejection.role}: ${rejection.comments}`
      : 'Submittal was rejected (no comments recorded).';

    // Compose the description for ai-rfi-draft. The function expects
    // ≥10 chars and returns subject + question + suggested_assignee.
    const draftPrompt =
      `Submittal "${submittal.title}" (spec section ${submittal.spec_section ?? 'unspecified'}, ` +
      `subcontractor ${submittal.subcontractor ?? 'unspecified'}) was rejected. ${rejectionContext} ` +
      `Draft an RFI to the architect requesting clarification on the path forward.`;

    let draftSubject = `RFI: clarification needed on rejected submittal — ${submittal.title}`;
    let draftQuestion = draftPrompt;
    let suggestedAssignee: string | undefined;

    try {
      const { data: aiResult } = await supabase.functions.invoke('ai-rfi-draft', {
        body: {
          description: draftPrompt,
          project_id: submittal.project_id,
        },
      });
      if (aiResult && typeof aiResult === 'object') {
        const r = aiResult as { subject?: string; question?: string; suggested_assignee?: string };
        if (r.subject) draftSubject = r.subject;
        if (r.question) draftQuestion = r.question;
        if (r.suggested_assignee) suggestedAssignee = r.suggested_assignee;
      }
    } catch (err) {
      // AI draft failed — fall through with our deterministic prompt as the question.
      console.warn('[submittal_rejected] ai-rfi-draft failed, using deterministic draft:', (err as Error).message);
    }

    const { data: insertedRfi, error: insertError } = await from('rfis')
      .insert({
        project_id: submittal.project_id,
        title: draftSubject,
        description: draftQuestion,
        status: 'draft',
        priority: 'medium',
        created_by: submittal.created_by,
        assigned_to: suggestedAssignee ?? null,
        ball_in_court: suggestedAssignee ?? null,
        drawing_reference: submittal.spec_section ?? null,
        metadata: { source: 'submittal_rejected', submittal_id: submittalId },
      } as unknown as Record<string, unknown>)
      .select('id')
      .single();

    if (insertError) return { workflow: 'submittal_rejected', error: insertError.message };
    return {
      workflow: 'submittal_rejected',
      created: { type: 'rfi', id: insertedRfi!.id as string },
    };
  } catch (err) {
    return { workflow: 'submittal_rejected', error: (err as Error).message };
  }
}

// ── L2#5: Daily-log incident entry → safety incident auto-create ───────────
//
// Fires from: code that inserts a daily_log_entries row of type 'incident'.
// Creates a corresponding incidents row pre-populated from the entry's
// description so the safety team has a real record to investigate, not
// just a line buried in a daily log. Idempotent via incidents.metadata.
//
// Why both rows: daily_log_entries.incident is the field-captured note;
// incidents is the OSHA-recordable formal record. They serve different
// audiences and lifecycles. The link lets users jump back to the source.

export async function runDailyLogIncidentChain(entryId: string): Promise<WorkflowResult> {
  try {
    const { data: entry, error: entryErr } = await from('daily_log_entries')
      .select('id, daily_log_id, type, description, created_at')
      .eq('id', entryId)
      .maybeSingle();
    if (entryErr) return { workflow: 'daily_log_incident', error: entryErr.message };
    if (!entry) return { workflow: 'daily_log_incident', error: 'entry not found' };
    if (entry.type !== 'incident') {
      return { workflow: 'daily_log_incident', skipped: { reason: 'entry is not an incident' } };
    }

    // The schema's daily_log_entries.type CHECK constraint doesn't include
    // 'safety', so the "Safety Meeting" quick-add preset reuses type='incident'
    // (see src/machines/dailyLogMachine.ts QUICK_ADD_PRESETS). Skip those —
    // a toolbox talk is not an OSHA-recordable event.
    const desc = ((entry.description as string | null) ?? '').toLowerCase();
    if (/\b(toolbox talk|safety meeting|safety briefing|tailgate)\b/.test(desc)) {
      return {
        workflow: 'daily_log_incident',
        skipped: { reason: 'description indicates a safety meeting, not an incident' },
      };
    }

    const { data: log } = await from('daily_logs')
      .select('project_id, log_date')
      .eq('id', entry.daily_log_id as string)
      .maybeSingle();
    if (!log) return { workflow: 'daily_log_incident', error: 'parent daily log not found' };

    // Skip if an incident already exists for this entry. jsonb containment.
    const { data: existing } = await from('incidents')
      .select('id')
      .eq('project_id', log.project_id as string)
      .contains('metadata', { daily_log_entry_id: entryId })
      .maybeSingle();
    if (existing) {
      return { workflow: 'daily_log_incident', skipped: { reason: `incident already exists for entry ${entryId}` } };
    }

    const description = (entry.description as string | null) ?? 'Incident reported in daily log (no description).';
    const { data: insertedIncident, error: insertErr } = await from('incidents')
      .insert({
        project_id: log.project_id,
        type: 'near_miss',     // Default — investigator can re-classify on review.
        severity: 'first_aid', // Same.
        // log_date is the canonical "what day did this happen" — fall back
        // to created_at, then today, so we never insert null (incidents.date
        // is NOT NULL in the schema).
        date: (log.log_date as string | null) ?? (entry.created_at as string | null) ?? new Date().toISOString().slice(0, 10),
        description,
        investigation_status: 'open',
        metadata: { source: 'daily_log_incident', daily_log_entry_id: entryId, daily_log_id: entry.daily_log_id },
      } as unknown as Record<string, unknown>)
      .select('id')
      .single();

    if (insertErr) return { workflow: 'daily_log_incident', error: insertErr.message };
    return {
      workflow: 'daily_log_incident',
      created: { type: 'incident', id: insertedIncident!.id as string },
    };
  } catch (err) {
    return { workflow: 'daily_log_incident', error: (err as Error).message };
  }
}

// ── Workflow #4: Drawing revised → flag affected RFIs ────────────────────
// When a new drawing is uploaded for a sheet number that already exists in
// the project, that's a revision. Any open RFI whose `drawing_reference`
// mentions the sheet number is potentially affected and the team should
// review it. We tag affected RFIs with metadata.affected_by_revision so
// the drawings page can surface a banner; we DO NOT auto-create or auto-
// modify RFIs (the team needs to make the judgment call).
//
// Idempotent: re-running for the same revision drawing is a no-op because
// the metadata key includes the revision drawing's id.
//
// Trigger: drawingService.createDrawing → after a successful insert with
// non-null sheet_number.
export interface DrawingRevisedResult extends WorkflowResult {
  workflow: 'drawing_revised';
  affectedRfiIds?: string[];
}

export async function runDrawingRevisedChain(
  newDrawingId: string,
): Promise<DrawingRevisedResult> {
  try {
    const { data: newDrawing } = await from('drawings')
      .select('id, project_id, sheet_number, revision, title')
      .eq('id', newDrawingId)
      .maybeSingle();
    if (!newDrawing) {
      return { workflow: 'drawing_revised', error: 'drawing not found' };
    }
    const sheetNumber = newDrawing.sheet_number as string | null;
    if (!sheetNumber) {
      return {
        workflow: 'drawing_revised',
        skipped: { reason: 'no sheet_number — cannot infer revision relationship' },
      };
    }

    // Determine whether this is actually a revision (i.e. another drawing
    // with the same sheet_number existed first). If this is the *first*
    // drawing for the sheet, there's nothing to flag.
    const { data: priorDrawings } = await from('drawings')
      .select('id, created_at')
      .eq('project_id', newDrawing.project_id as string)
      .eq('sheet_number', sheetNumber)
      .neq('id', newDrawingId)
      .limit(1);
    if (!priorDrawings || priorDrawings.length === 0) {
      return {
        workflow: 'drawing_revised',
        skipped: { reason: 'no prior drawing with this sheet_number — first upload, not a revision' },
      };
    }

    // Find open RFIs whose drawing_reference contains the sheet number.
    // Use ilike for case-insensitive match. drawing_reference is free text
    // (e.g. "A4.20" or "see A4.20 detail 3") so substring match is right.
    // Status values validated against migration 00028_rfi_workflow.sql:
    // CHECK (status IN ('draft','open','under_review','answered','closed','void')).
    const { data: candidateRfis } = await from('rfis')
      .select('id, drawing_reference, metadata, status')
      .eq('project_id', newDrawing.project_id as string)
      .in('status', ['draft', 'open', 'under_review'])
      .ilike('drawing_reference', `%${sheetNumber}%`);

    if (!candidateRfis || candidateRfis.length === 0) {
      return { workflow: 'drawing_revised', skipped: { reason: 'no open RFIs reference this sheet' } };
    }

    // Idempotency: skip RFIs already flagged for this exact revision drawing.
    const toFlag = (candidateRfis as any[]).filter((rfi) => {
      const existing = (rfi.metadata as unknown as Record<string, unknown> | null) ?? {};
      const flags = (existing.affected_by_revisions as string[] | undefined) ?? [];
      return !flags.includes(newDrawingId);
    });
    if (toFlag.length === 0) {
      return { workflow: 'drawing_revised', skipped: { reason: 'all candidate RFIs already flagged' } };
    }

    // Append to the metadata.affected_by_revisions array on each affected RFI.
    // We update one at a time — there's no PostgREST shortcut for "append to
    // a jsonb array" in a bulk update without raw SQL, and the volume is low.
    const flagged: string[] = [];
    for (const rfi of toFlag) {
      const existingMeta = (rfi.metadata as unknown as Record<string, unknown> | null) ?? {};
      const existingFlags = (existingMeta.affected_by_revisions as string[] | undefined) ?? [];
      const newMeta = {
        ...existingMeta,
        affected_by_revisions: [...existingFlags, newDrawingId],
        last_revision_flagged_at: new Date().toISOString(),
      };
      const { error: updateError } = await from('rfis')
        .update({ metadata: newMeta } as never)
        .eq('id', rfi.id);
      if (!updateError) flagged.push(rfi.id as string);
    }

    return {
      workflow: 'drawing_revised',
      affectedRfiIds: flagged,
    };
  } catch (err) {
    return { workflow: 'drawing_revised', error: (err as Error).message };
  }
}

// ── L2#4: Schedule slip → AI-draft change order ────────────────────────────
//
// Fires from: scheduleService.updateTask after a meaningful end_date or
// estimated_hours drift vs the task's original baseline. We treat a slip
// of ≥ 5 days as material (configurable). Drafts a change order with a
// schedule_impact_days field and a placeholder estimated_cost (the team
// fills in the real number after pricing).
//
// Idempotent via change_orders.metadata @> { task_id, slip_signature }
// where slip_signature is a hash of (task_id, new_end_date, days_added).
// This lets a 7-day slip later become a 14-day slip and still trigger
// a fresh CO instead of being skipped as a duplicate.
//
// Required schema: change_orders.metadata (see migration
// 20260429000001_change_order_metadata.sql).

export interface ScheduleSlipInput {
  taskId: string;
  projectId: string;
  baselineEndDate: string | null; // ISO date — what we thought it would end
  newEndDate: string;             // ISO date — what it now ends
  estimatedHoursDelta?: number;   // hours added vs baseline (optional)
}

const SCHEDULE_SLIP_THRESHOLD_DAYS = 5;
const HOURLY_RATE_PLACEHOLDER = 75; // $/hr — generic skilled labor; teams adjust

export async function runScheduleSlipChain(
  input: ScheduleSlipInput,
): Promise<WorkflowResult> {
  try {
    const { taskId, projectId, baselineEndDate, newEndDate, estimatedHoursDelta } = input;
    if (!baselineEndDate) {
      return { workflow: 'schedule_slip', skipped: { reason: 'no baseline end date' } };
    }
    const daysAdded = Math.floor(
      (new Date(newEndDate).getTime() - new Date(baselineEndDate).getTime()) / 86_400_000,
    );
    if (daysAdded < SCHEDULE_SLIP_THRESHOLD_DAYS) {
      return {
        workflow: 'schedule_slip',
        skipped: { reason: `slip ${daysAdded}d is below threshold (${SCHEDULE_SLIP_THRESHOLD_DAYS}d)` },
      };
    }

    const { data: task } = await from('tasks')
      .select('id, title, description, trade')
      .eq('id', taskId)
      .maybeSingle();
    if (!task) return { workflow: 'schedule_slip', error: 'task not found' };

    // Slip signature lets the same task generate a new CO when the slip
    // grows. Initial slip of 7d → CO drafted; if it later grows to 14d
    // we want a new CO, not a skip. The signature includes the rounded
    // newEndDate (week granularity) to debounce minor adjustments.
    const slipSignature = `${taskId}:${daysAdded}:${newEndDate.slice(0, 10)}`;
    const { data: existing } = await from('change_orders')
      .select('id')
      .eq('project_id', projectId)
      .contains('metadata', { slip_signature: slipSignature })
      .maybeSingle();
    if (existing) {
      return {
        workflow: 'schedule_slip',
        skipped: { reason: `CO already drafted for slip signature ${slipSignature}` },
      };
    }

    const estimatedCost = estimatedHoursDelta != null
      ? Math.round(estimatedHoursDelta * HOURLY_RATE_PLACEHOLDER)
      : null;

    const description =
      `Schedule slip detected on task "${task.title}"` +
      (task.trade ? ` (${task.trade})` : '') +
      `. Original end date: ${baselineEndDate}. Revised end date: ${newEndDate} ` +
      `(${daysAdded} days added).` +
      (estimatedHoursDelta != null
        ? ` Estimated additional labor: ${estimatedHoursDelta} hours @ $${HOURLY_RATE_PLACEHOLDER}/hr placeholder.`
        : '') +
      ` Auto-generated by schedule-slip detector — review and complete pricing before submitting.`;

    const { data: insertedCo, error: insertErr } = await from('change_orders')
      .insert({
        project_id: projectId,
        title: `Schedule slip: ${task.title}`,
        description,
        status: 'draft',
        type: 'time_only',
        reason: 'schedule_slip',
        reason_code: 'schedule_extension',
        schedule_impact: `${daysAdded} days added`,
        schedule_impact_days: daysAdded,
        estimated_cost: estimatedCost,
        amount: estimatedCost,
        requested_date: new Date().toISOString().slice(0, 10),
        metadata: {
          source: 'schedule_slip_chain',
          task_id: taskId,
          slip_signature: slipSignature,
          baseline_end_date: baselineEndDate,
          new_end_date: newEndDate,
          days_added: daysAdded,
        },
      } as unknown as Record<string, unknown>)
      .select('id')
      .single();

    if (insertErr) return { workflow: 'schedule_slip', error: insertErr.message };
    return {
      workflow: 'schedule_slip',
      created: { type: 'change_order', id: insertedCo!.id as string },
    };
  } catch (err) {
    return { workflow: 'schedule_slip', error: (err as Error).message };
  }
}

// ── L1#5: Drawing discrepancy → AI-draft RFI ───────────────────────────────
//
// Fires from: useDrawingIntelligence after analyze-discrepancies completes
// and reports a high-severity coordinate mismatch. Calls ai-rfi-draft with
// the discrepancy context (location, disciplines involved, deltas) and
// inserts a draft RFI tagged to the source discrepancy. Idempotent via
// rfis.metadata.discrepancy_id.

export async function runDiscrepancyDetectedChain(
  discrepancyId: string,
): Promise<WorkflowResult> {
  try {
    const { data: discrepancy } = await from('drawing_discrepancies')
      .select('id, pair_id, severity, description, location_label, dimension_diff, project_id')
      .eq('id', discrepancyId)
      .maybeSingle();
    if (!discrepancy) {
      return { workflow: 'discrepancy_detected', error: 'discrepancy not found' };
    }
    // Skip low-severity — too noisy to auto-RFI everything.
    if (discrepancy.severity && !['high', 'critical'].includes(discrepancy.severity as string)) {
      return {
        workflow: 'discrepancy_detected',
        skipped: { reason: `severity ${discrepancy.severity} is below auto-RFI threshold` },
      };
    }

    // Idempotency: skip if an RFI already exists for this discrepancy.
    const { data: existing } = await from('rfis')
      .select('id')
      .eq('project_id', discrepancy.project_id as string)
      .contains('metadata', { discrepancy_id: discrepancyId })
      .maybeSingle();
    if (existing) {
      return {
        workflow: 'discrepancy_detected',
        skipped: { reason: `rfi already exists for discrepancy ${discrepancyId}` },
      };
    }

    const draftPrompt =
      `Drawing discrepancy detected at ${discrepancy.location_label ?? 'unspecified location'}: ` +
      `${discrepancy.description ?? 'coordinate mismatch'}` +
      (discrepancy.dimension_diff ? ` (delta: ${discrepancy.dimension_diff})` : '') +
      `. Severity: ${discrepancy.severity ?? 'unspecified'}. ` +
      `Draft an RFI to the architect requesting clarification.`;

    let draftSubject = `RFI: drawing discrepancy at ${discrepancy.location_label ?? 'specified location'}`;
    let draftQuestion = draftPrompt;
    let suggestedAssignee: string | undefined;

    try {
      const { data: aiResult } = await supabase.functions.invoke('ai-rfi-draft', {
        body: {
          description: draftPrompt,
          project_id: discrepancy.project_id,
        },
      });
      if (aiResult && typeof aiResult === 'object') {
        const r = aiResult as { subject?: string; question?: string; suggested_assignee?: string };
        if (r.subject) draftSubject = r.subject;
        if (r.question) draftQuestion = r.question;
        if (r.suggested_assignee) suggestedAssignee = r.suggested_assignee;
      }
    } catch (err) {
      console.warn(
        '[discrepancy_detected] ai-rfi-draft failed, using deterministic draft:',
        (err as Error).message,
      );
    }

    const { data: insertedRfi, error: insertError } = await from('rfis')
      .insert({
        project_id: discrepancy.project_id,
        title: draftSubject,
        description: draftQuestion,
        status: 'draft',
        priority: discrepancy.severity === 'critical' ? 'critical' : 'high',
        assigned_to: suggestedAssignee ?? null,
        ball_in_court: suggestedAssignee ?? null,
        is_auto_generated: true,
        source_discrepancy_id: discrepancyId,
        metadata: { source: 'discrepancy_detected', discrepancy_id: discrepancyId },
      } as unknown as Record<string, unknown>)
      .select('id')
      .single();

    if (insertError) return { workflow: 'discrepancy_detected', error: insertError.message };
    return {
      workflow: 'discrepancy_detected',
      created: { type: 'rfi', id: insertedRfi!.id as string },
    };
  } catch (err) {
    return { workflow: 'discrepancy_detected', error: (err as Error).message };
  }
}

// ── L2#6: Daily-log delay → schedule-shift suggestion ──────────────────────
//
// Fires from: useCreateDailyLogEntry when the entry's type is 'delay'.
// Finds tasks whose start_date or end_date falls within the delay's date
// window and posts a suggestion to activity_feed (the canonical surface
// for ambient cross-feature signals — already has a metadata column and
// is consumed by the dashboard "Recent activity" feed).
//
// Idempotent via activity_feed.metadata.daily_log_entry_id.
//
// We deliberately DO NOT auto-update task dates. Construction PMs need
// to make that call themselves; we surface the candidates and let them
// decide which to shift.

export async function runDailyLogDelayChain(entryId: string): Promise<WorkflowResult> {
  try {
    const { data: entry } = await from('daily_log_entries')
      .select('id, daily_log_id, type, description, delay_cause, delay_hours')
      .eq('id', entryId)
      .maybeSingle();
    if (!entry) return { workflow: 'daily_log_delay', error: 'entry not found' };
    if (entry.type !== 'delay') {
      return { workflow: 'daily_log_delay', skipped: { reason: 'entry is not a delay' } };
    }

    const { data: log } = await from('daily_logs')
      .select('project_id, log_date')
      .eq('id', entry.daily_log_id as string)
      .maybeSingle();
    if (!log) return { workflow: 'daily_log_delay', error: 'parent daily log not found' };

    // Idempotency
    const { data: existing } = await from('activity_feed')
      .select('id')
      .eq('project_id', log.project_id as string)
      .contains('metadata', { daily_log_entry_id: entryId })
      .maybeSingle();
    if (existing) {
      return {
        workflow: 'daily_log_delay',
        skipped: { reason: `activity_feed entry already exists for delay ${entryId}` },
      };
    }

    // Find tasks active on the log_date — start_date <= log_date <= end_date.
    const logDate = log.log_date as string;
    const { data: affectedTasks } = await from('tasks')
      .select('id, title, start_date, end_date')
      .eq('project_id', log.project_id as string)
      .lte('start_date', logDate)
      .gte('end_date', logDate);

    const delayHours = (entry.delay_hours as number | null) ?? 0;
    const suggestedDays = Math.max(1, Math.ceil(delayHours / 8));
    const taskList = (affectedTasks as { id: string; title: string }[] | null) ?? [];

    const taskSummary = taskList.length === 0
      ? 'No tasks were scheduled for this date.'
      : taskList.length === 1
        ? `1 task affected: "${taskList[0].title}".`
        : `${taskList.length} tasks affected: ${taskList
            .slice(0, 3)
            .map((t) => `"${t.title}"`)
            .join(', ')}${taskList.length > 3 ? `, +${taskList.length - 3} more` : ''}.`;

    const body =
      `Delay logged on ${logDate}` +
      (entry.delay_cause ? ` (cause: ${entry.delay_cause})` : '') +
      ` for ${delayHours} hours. ${taskSummary} ` +
      `Suggested action: review affected tasks and shift end_date by ~${suggestedDays} day(s) where appropriate.`;

    const { data: inserted, error: insertErr } = await from('activity_feed')
      .insert({
        project_id: log.project_id,
        type: 'schedule_shift_suggestion',
        title: `Schedule shift suggested — ${suggestedDays}d delay`,
        body,
        metadata: {
          source: 'daily_log_delay_chain',
          daily_log_entry_id: entryId,
          daily_log_id: entry.daily_log_id,
          delay_hours: delayHours,
          suggested_shift_days: suggestedDays,
          affected_task_ids: taskList.map((t) => t.id),
        },
      } as unknown as Record<string, unknown>)
      .select('id')
      .single();

    if (insertErr) return { workflow: 'daily_log_delay', error: insertErr.message };
    return {
      workflow: 'daily_log_delay',
      created: { type: 'activity', id: inserted!.id as string },
    };
  } catch (err) {
    return { workflow: 'daily_log_delay', error: (err as Error).message };
  }
}

// ── L2#8: Meeting action item → task auto-create ──────────────────────────
//
// Sweep-style: scans the project for meeting_action_items that have no
// linked_task_id and creates a task for each. Runs on dashboard mount
// alongside runRfiOverdueSweep. Idempotent because we update
// meeting_action_items.linked_task_id after the task is created — the
// next sweep skips it.
//
// Why a sweep instead of a per-insert hook: the codebase doesn't have
// a mutation hook for action items yet (only queries). A sweep covers
// items inserted by any path — UI, API, edge function, seed — without
// requiring every writer to dispatch the chain.

export async function runMeetingActionItemTaskSweep(
  projectId: string,
): Promise<WorkflowResult[]> {
  const results: WorkflowResult[] = [];
  try {
    // Pull action items in this project that don't yet have a task linked.
    // The schema: meeting_action_items has no project_id directly; it links
    // through meeting_id → meetings.project_id.
    const { data: pending } = await from('meeting_action_items')
      .select('id, description, assigned_to, due_date, priority, status, linked_task_id, meeting_id, meetings!inner(project_id, title)')
      .eq('meetings.project_id', projectId)
      .is('linked_task_id', null)
      .neq('status', 'completed')
      .limit(50);

    if (!pending || pending.length === 0) return results;

    for (const item of pending as any[]) {
      const meetingTitle =
        Array.isArray(item.meetings) ? item.meetings[0]?.title : item.meetings?.title;
      const description =
        `From meeting "${meetingTitle ?? 'unspecified'}".` +
        (item.description ? `\n\n${item.description}` : '');

      const { data: insertedTask, error: insertErr } = await from('tasks')
        .insert({
          project_id: projectId,
          title: item.description ? `Action: ${item.description.slice(0, 80)}` : 'Meeting action item',
          description,
          status: 'todo',
          priority: ['high', 'medium', 'low'].includes(item.priority as string)
            ? item.priority
            : 'medium',
          assigned_to: item.assigned_to ?? null,
          due_date: item.due_date ?? null,
          metadata: {
            source: 'meeting_action_item_sweep',
            action_item_id: item.id,
            meeting_id: item.meeting_id,
          },
        } as unknown as Record<string, unknown>)
        .select('id')
        .single();

      if (insertErr) {
        results.push({ workflow: 'meeting_action_item_sweep', error: insertErr.message });
        continue;
      }
      if (!insertedTask) continue;

      // Link the action item back to the new task. If this update fails,
      // we'll create another task on the next sweep — the metadata.action_item_id
      // wouldn't save us because tasks lacks a unique constraint on it.
      // To prevent that, double-check the action item still has no link
      // (cheap defense against a concurrent run).
      await from('meeting_action_items')
        .update({ linked_task_id: insertedTask.id } as never)
        .eq('id', item.id)
        .is('linked_task_id', null);

      results.push({
        workflow: 'meeting_action_item_sweep',
        created: { type: 'task', id: insertedTask.id as string },
      });
    }
    return results;
  } catch (err) {
    results.push({ workflow: 'meeting_action_item_sweep', error: (err as Error).message });
    return results;
  }
}

// ── L2#12: Submittal approved → procurement-order suggestion ───────────────
//
// Fires from: submittalService.transitionStatus when newStatus === 'approved'.
// The schema doesn't have a procurement_orders table today, so we route the
// suggestion through activity_feed (same pattern as L2#6). The body includes
// the lead_time_weeks (so the buyout date can be back-calculated) and the
// subcontractor (so the team knows who to contact).

export async function runSubmittalApprovedChain(
  submittalId: string,
): Promise<WorkflowResult> {
  try {
    const { data: submittal } = await from('submittals')
      .select('id, project_id, title, spec_section, subcontractor, lead_time_weeks, approved_date, required_onsite_date')
      .eq('id', submittalId)
      .maybeSingle();
    if (!submittal) return { workflow: 'submittal_approved', error: 'submittal not found' };

    // Idempotency
    const { data: existing } = await from('activity_feed')
      .select('id')
      .eq('project_id', submittal.project_id as string)
      .contains('metadata', { submittal_id: submittalId, source: 'submittal_approved_chain' })
      .maybeSingle();
    if (existing) {
      return {
        workflow: 'submittal_approved',
        skipped: { reason: `procurement suggestion already exists for submittal ${submittalId}` },
      };
    }

    // Lead-time math.
    //   • If we know when the material is needed onsite, buyout_by_date is
    //     onsite − lead_time_weeks (the canonical construction-PM formula).
    //   • Otherwise project forward from approval: delivery would land
    //     today + lead_time_weeks, and the buyout window is "now."
    const leadWeeks = submittal.lead_time_weeks as number | null;
    const onsite = submittal.required_onsite_date as string | null;
    const leadMs = leadWeeks != null ? leadWeeks * 7 * 86_400_000 : 0;
    const buyoutByDate =
      leadWeeks != null && onsite
        ? new Date(new Date(onsite).getTime() - leadMs).toISOString().slice(0, 10)
        : null;
    const deliveryEta =
      leadWeeks != null && !onsite
        ? new Date(Date.now() + leadMs).toISOString().slice(0, 10)
        : null;

    const body =
      `Submittal "${submittal.title}" approved` +
      (submittal.subcontractor ? ` (vendor: ${submittal.subcontractor})` : '') +
      `. Issue procurement order to lock pricing and delivery window.` +
      (leadWeeks != null
        ? buyoutByDate
          ? ` Lead time ${leadWeeks} weeks — buyout by ${buyoutByDate} to hold the schedule.`
          : ` Lead time ${leadWeeks} weeks — release PO now; expected delivery ~${deliveryEta}.`
        : '');

    const { data: inserted, error: insertErr } = await from('activity_feed')
      .insert({
        project_id: submittal.project_id,
        type: 'procurement_suggestion',
        title: `Procurement suggested — ${submittal.title}`,
        body,
        metadata: {
          source: 'submittal_approved_chain',
          submittal_id: submittalId,
          subcontractor: submittal.subcontractor,
          lead_time_weeks: leadWeeks,
          buyout_by_date: buyoutByDate,
          delivery_eta: deliveryEta,
        },
      } as unknown as Record<string, unknown>)
      .select('id')
      .single();

    if (insertErr) return { workflow: 'submittal_approved', error: insertErr.message };
    return {
      workflow: 'submittal_approved',
      created: { type: 'activity', id: inserted!.id as string },
    };
  } catch (err) {
    return { workflow: 'submittal_approved', error: (err as Error).message };
  }
}

// ── L2#10: Punch zone cleared → closeout coverage advance ──────────────────
//
// Fires from: punchItemService.transitionStatus when status moves to
// 'verified' (the terminal punch state). We check whether this was the
// LAST open punch in the item's `area`. If so, post an activity_feed
// entry signalling closeout coverage advance for that zone.
//
// Schema constraint: punch_items has no zone_id; zones are identified by
// the free-text `area` column. Match is case-insensitive exact.

export async function runPunchVerifiedChain(
  punchItemId: string,
): Promise<WorkflowResult> {
  try {
    const { data: punch } = await from('punch_items')
      .select('id, project_id, area, status')
      .eq('id', punchItemId)
      .maybeSingle();
    if (!punch) return { workflow: 'punch_verified', error: 'punch item not found' };
    if (punch.status !== 'verified') {
      return { workflow: 'punch_verified', skipped: { reason: 'punch is not verified' } };
    }
    const area = (punch.area as string | null) ?? null;
    if (!area) {
      return { workflow: 'punch_verified', skipped: { reason: 'punch has no area — cannot determine zone' } };
    }

    // Are there any open/in_progress/resolved (non-verified) punches still
    // in this area? If yes, the zone isn't cleared yet.
    const { data: openInArea } = await from('punch_items')
      .select('id')
      .eq('project_id', punch.project_id as string)
      .ilike('area', area)
      .in('status', ['open', 'in_progress', 'resolved'])
      .limit(1);
    if (openInArea && openInArea.length > 0) {
      return {
        workflow: 'punch_verified',
        skipped: { reason: `${openInArea.length}+ open punches remain in area "${area}"` },
      };
    }

    // Idempotency: skip if we already announced coverage for this area.
    const { data: existing } = await from('activity_feed')
      .select('id')
      .eq('project_id', punch.project_id as string)
      .contains('metadata', { source: 'punch_verified_chain', area: area.toLowerCase() })
      .maybeSingle();
    if (existing) {
      return {
        workflow: 'punch_verified',
        skipped: { reason: `closeout advance already posted for area "${area}"` },
      };
    }

    const { data: inserted, error: insertErr } = await from('activity_feed')
      .insert({
        project_id: punch.project_id,
        type: 'closeout_coverage_advance',
        title: `Zone cleared: ${area}`,
        body: `All punch items in "${area}" are verified. Closeout coverage advances for this zone.`,
        metadata: {
          source: 'punch_verified_chain',
          area: area.toLowerCase(),
          last_punch_id: punchItemId,
        },
      } as unknown as Record<string, unknown>)
      .select('id')
      .single();

    if (insertErr) return { workflow: 'punch_verified', error: insertErr.message };
    return {
      workflow: 'punch_verified',
      created: { type: 'activity', id: inserted!.id as string },
    };
  } catch (err) {
    return { workflow: 'punch_verified', error: (err as Error).message };
  }
}

// ── L2#7: Permit approved → schedule milestone unlock ──────────────────────
//
// Fires from: code that transitions a permit to status='approved' or
// 'issued' (the issuance is the unlock signal — 'approved' means the city
// said yes, 'issued' means the team has the permit in hand).
//
// We don't have a permit→task linkage table. We post an activity_feed
// entry calling out the permit type so the PM can find the gated tasks.
// Idempotent via activity_feed.metadata.permit_id.

export async function runPermitApprovedChain(
  permitId: string,
): Promise<WorkflowResult> {
  try {
    const { data: permit } = await from('permits')
      .select('id, project_id, type, status, permit_number, jurisdiction, issued_date, expiration_date')
      .eq('id', permitId)
      .maybeSingle();
    if (!permit) return { workflow: 'permit_approved', error: 'permit not found' };
    if (!['approved', 'issued'].includes(permit.status as string)) {
      return {
        workflow: 'permit_approved',
        skipped: { reason: `permit status is ${permit.status}, not approved/issued` },
      };
    }

    // Idempotency
    const { data: existing } = await from('activity_feed')
      .select('id')
      .eq('project_id', permit.project_id as string)
      .contains('metadata', { source: 'permit_approved_chain', permit_id: permitId })
      .maybeSingle();
    if (existing) {
      return {
        workflow: 'permit_approved',
        skipped: { reason: `unlock notice already posted for permit ${permitId}` },
      };
    }

    const permitType = (permit.type as string | null) ?? 'permit';
    const permitNumber = (permit.permit_number as string | null) ?? '(no number)';
    const expires = (permit.expiration_date as string | null) ?? null;

    const body =
      `${permitType} permit ${permitNumber}` +
      (permit.jurisdiction ? ` (${permit.jurisdiction})` : '') +
      ` is now ${permit.status}. Tasks gated on this permit can proceed.` +
      (expires ? ` Permit expires ${expires}.` : '');

    const { data: inserted, error: insertErr } = await from('activity_feed')
      .insert({
        project_id: permit.project_id,
        type: 'permit_unlock',
        title: `Permit ${permit.status}: ${permitType}`,
        body,
        metadata: {
          source: 'permit_approved_chain',
          permit_id: permitId,
          permit_type: permitType,
          permit_number: permitNumber,
          expiration_date: expires,
        },
      } as unknown as Record<string, unknown>)
      .select('id')
      .single();

    if (insertErr) return { workflow: 'permit_approved', error: insertErr.message };
    return {
      workflow: 'permit_approved',
      created: { type: 'activity', id: inserted!.id as string },
    };
  } catch (err) {
    return { workflow: 'permit_approved', error: (err as Error).message };
  }
}

// ── Tab A: Crew no-show → meeting action item ─────────────────────────────
//
// Fires from: the daily-log expected-vs-actual widget when the GC taps
// "Create action item" on a 60+ min late crew. Idempotent via crew_attendance
// (one row per crew_id+date, with meeting_action_item_id back-linking).
//
// We intentionally route through meetings/action_items (rather than a flat
// task) because no-show calls naturally belong on a daily standup agenda
// and the existing action-item sweep then converts them to tasks if the
// PM doesn't close them within the day.

export async function runCrewNoShowChain(input: {
  crewId: string;
  projectId: string;
  date: string; // ISO YYYY-MM-DD
}): Promise<WorkflowResult> {
  try {
    const { crewId, projectId, date } = input;

    // Idempotency: if today's attendance row already has a linked action
    // item, this chain has already fired.
    const { data: attendance } = await from('crew_attendance')
      .select('id, meeting_action_item_id, no_show_flagged_at')
      .eq('crew_id', crewId)
      .eq('attendance_date', date)
      .maybeSingle();
    if (attendance?.meeting_action_item_id) {
      return { workflow: 'crew_no_show', skipped: { reason: 'action item already created for this crew today' } };
    }

    // Pull the crew details for the action-item description.
    const { data: crew } = await from('crews')
      .select('id, name, trade, lead_id, planned_arrival_time, project_id')
      .eq('id', crewId)
      .maybeSingle();
    if (!crew) return { workflow: 'crew_no_show', error: 'crew not found' };

    // Find the most recent meeting in this project to attach the action
    // item to. If there's no meeting, fall through and use a placeholder
    // meeting_id of the crew_id (the action-item sweep will still pick it
    // up — it doesn't require a real meeting). Schema requires meeting_id
    // NOT NULL though, so we skip if there's truly no meeting yet.
    const { data: meeting } = await from('meetings')
      .select('id')
      .eq('project_id', projectId)
      .order('meeting_date', { ascending: false })
      .limit(1)
      .maybeSingle();
    if (!meeting) {
      // Without a meeting we can't attach an action item, so we just
      // mark the no-show on the attendance row. The widget will show
      // "Flagged" instead of "Create action item" so the GC can call
      // the foreman manually.
      const nowIso = new Date().toISOString();
      if (attendance) {
        await from('crew_attendance')
          .update({ no_show_flagged_at: nowIso } as never)
          .eq('id', attendance.id);
      } else {
        await from('crew_attendance').insert({
          project_id: projectId,
          crew_id: crewId,
          attendance_date: date,
          planned_arrival_time: crew.planned_arrival_time,
          no_show_flagged_at: nowIso,
        } as never);
      }
      return { workflow: 'crew_no_show', skipped: { reason: 'no meeting exists yet — flagged on attendance row only' } };
    }

    const description =
      `Call ${crew.name}${crew.trade ? ` (${crew.trade})` : ''} — 60+ min late on ${date}.` +
      (crew.planned_arrival_time ? ` Planned arrival: ${crew.planned_arrival_time}.` : '');

    const { data: insertedItem, error: insertErr } = await from('meeting_action_items')
      .insert({
        meeting_id: meeting.id,
        description,
        priority: 'high',
        status: 'open',
        due_date: date,
      } as unknown as Record<string, unknown>)
      .select('id')
      .single();

    if (insertErr) return { workflow: 'crew_no_show', error: insertErr.message };
    if (!insertedItem) return { workflow: 'crew_no_show', error: 'insert returned no row' };

    // Back-link onto crew_attendance — creating the row if it doesn't exist.
    const nowIso = new Date().toISOString();
    if (attendance) {
      await from('crew_attendance')
        .update({
          no_show_flagged_at: nowIso,
          meeting_action_item_id: insertedItem.id,
        } as never)
        .eq('id', attendance.id);
    } else {
      await from('crew_attendance').insert({
        project_id: projectId,
        crew_id: crewId,
        attendance_date: date,
        planned_arrival_time: crew.planned_arrival_time,
        no_show_flagged_at: nowIso,
        meeting_action_item_id: insertedItem.id,
      } as never);
    }

    return {
      workflow: 'crew_no_show',
      created: { type: 'task', id: insertedItem.id as string },
    };
  } catch (err) {
    return { workflow: 'crew_no_show', error: (err as Error).message };
  }
}
