// Shared builders used by both scripts/generate-permissions-sql.ts (writer)
// and scripts/check-permissions-sync.ts (drift detector). The check works
// by re-building expected artifacts and byte-comparing against on-disk
// files — duplicating these builders would let the two scripts silently
// diverge and rubber-stamp drift, so they live here.

import {
  ROLES,
  ROLE_HIERARCHY,
  PERMISSION_MATRIX,
  MODULE_PERMISSIONS,
  type Permission,
} from '../../src/permissions'

const SQL_HEADER = `-- AUTOGENERATED from src/permissions.ts by scripts/generate-permissions-sql.ts
-- DO NOT EDIT MANUALLY. Run \`npm run permissions:generate\` to regenerate.
-- Drift detector: \`npm run permissions:check\`.`

export function buildSql(): string {
  const roleList = ROLES.map((r) => `'${r}'`).join(', ')
  const caseBranches = ROLES.map((r) => `    WHEN '${r}' THEN ${ROLE_HIERARCHY[r]}`).join('\n')

  return `${SQL_HEADER}

-- ── Expand project_members.role CHECK from 6 → 15 roles ──────
ALTER TABLE project_members DROP CONSTRAINT IF EXISTS project_members_role_check;
ALTER TABLE project_members ADD CONSTRAINT project_members_role_check
  CHECK (role IN (${roleList}));

-- ── has_project_permission: 15-role hierarchy ───────────────
-- Existing roles' relative ordering is preserved (owner > admin > project_manager
-- > superintendent > subcontractor > viewer), so existing RLS policies that call
-- this function return the same boolean. Numeric levels shift (owner: 6→7, admin:
-- 5→6, project_manager: 4→5, superintendent: 3→4) but no policy hard-codes them.
--
-- BEHAVIOR NOTE: roles previously absent from the CASE (foreman, project_engineer,
-- field_engineer, safety_manager, project_executive, architect, owner_rep, member,
-- field_user) used to fall through to \`ELSE 0\`, making any policy that passed
-- one of them as p_min_role a no-op (always returned true since every authenticated
-- role had role_level >= 1). They now have explicit hierarchy levels. The most
-- visible side effect: equipment service policies in
-- 20260417000008_equipment_service_layer.sql at lines 128/134/192 pass 'foreman'
-- as p_min_role; the gate now correctly enforces level-3+ access. Roles at level 2
-- (subcontractor, architect, owner_rep, member, field_user) lose equipment write
-- access — restoring the policy author's original intent.
CREATE OR REPLACE FUNCTION has_project_permission(p_project_id uuid, p_min_role text)
RETURNS boolean AS $$
DECLARE
  user_role text;
  role_level int;
  min_level int;
BEGIN
  SELECT role INTO user_role FROM project_members
  WHERE project_id = p_project_id AND user_id = auth.uid();

  IF user_role IS NULL THEN RETURN false; END IF;

  role_level := CASE user_role
${caseBranches}
    ELSE 0
  END;

  min_level := CASE p_min_role
${caseBranches}
    ELSE 0
  END;

  RETURN role_level >= min_level;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER STABLE;
`
}

export function buildEdgeMirror(): string {
  const rolesLiteral = ROLES.map((r) => `  '${r}',`).join('\n')
  const hierarchyEntries = ROLES.map((r) => `  ${r}: ${ROLE_HIERARCHY[r]},`).join('\n')

  const permissions = Object.keys(PERMISSION_MATRIX) as Permission[]
  const permissionUnion = permissions.map((p) => `  | '${p}'`).join('\n')
  const matrixEntries = permissions
    .map((p) => {
      const allowed = PERMISSION_MATRIX[p].map((r) => `'${r}'`).join(', ')
      return `  '${p}': [${allowed}],`
    })
    .join('\n')
  const moduleEntries = Object.entries(MODULE_PERMISSIONS)
    .map(([k, v]) => `  ${JSON.stringify(k)}: '${v}',`)
    .join('\n')

  return `// AUTOGENERATED from src/permissions.ts by scripts/generate-permissions-sql.ts
// DO NOT EDIT MANUALLY. Run \`npm run permissions:generate\` to regenerate.
// Drift detector: \`npm run permissions:check\`.
//
// Deno-compatible edge mirror. Edge functions (supabase/functions/*) import
// from here:
//   import { can, getAllowedActions } from '../shared/permissions.ts'

export const ROLES = [
${rolesLiteral}
] as const

export type Role = typeof ROLES[number]

export const ROLE_HIERARCHY: Record<Role, number> = {
${hierarchyEntries}
}

export type Permission =
${permissionUnion}

export const PERMISSION_MATRIX: Record<Permission, readonly Role[]> = {
${matrixEntries}
}

export const MODULE_PERMISSIONS: Record<string, Permission> = {
${moduleEntries}
}

export function can(role: Role | null | undefined, action: Permission): boolean {
  if (!role) return false
  const allowed = PERMISSION_MATRIX[action]
  return allowed ? allowed.includes(role) : false
}

export function canAny(role: Role | null | undefined, actions: Permission[]): boolean {
  return actions.some((a) => can(role, a))
}

export function isAtLeast(role: Role | null | undefined, minRole: Role): boolean {
  if (!role) return false
  return ROLE_HIERARCHY[role] >= ROLE_HIERARCHY[minRole]
}

export function getAllowedActions(role: Role | null | undefined): Permission[] {
  if (!role) return []
  return (Object.keys(PERMISSION_MATRIX) as Permission[]).filter((a) => can(role, a))
}
`
}
