import React from 'react'
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'
import { colors, vizColors } from '../../styles/theme'

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: 'Helvetica',
    color: vizColors.darkText,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: colors.darkNavy,
  },
  headerLeft: {},
  logo: {
    fontSize: 16,
    fontFamily: 'Helvetica-Bold',
    color: colors.darkNavy,
  },
  projectName: {
    fontSize: 8,
    color: colors.textSecondary,
    marginTop: 2,
  },
  headerRight: {
    alignItems: 'flex-end' as const,
  },
  reportTitle: {
    fontSize: 14,
    fontFamily: 'Helvetica-Bold',
    color: colors.darkNavy,
  },
  reportDate: {
    fontSize: 8,
    color: colors.textSecondary,
    marginTop: 2,
  },
  footer: {
    position: 'absolute' as const,
    bottom: 20,
    left: 40,
    right: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: colors.borderDefault,
    paddingTop: 8,
  },
  footerText: {
    fontSize: 7,
    color: colors.textTertiary,
  },
  // Table styles
  table: {
    marginTop: 12,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: colors.darkNavy,
    padding: 6,
  },
  tableHeaderCell: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 8,
    color: colors.white,
  },
  tableRow: {
    flexDirection: 'row',
    padding: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.borderDefault,
  },
  tableRowAlt: {
    flexDirection: 'row',
    padding: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.borderDefault,
    backgroundColor: colors.surfacePage,
  },
  tableCell: {
    fontSize: 8,
    color: vizColors.darkText,
  },
  sectionTitle: {
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
    color: colors.darkNavy,
    marginTop: 20,
    marginBottom: 8,
  },
  badge: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
    padding: '2 6',
    borderRadius: 3,
  },
})

// Reusable header
interface PDFHeaderProps {
  projectName: string
  reportTitle: string
  date: string
}

export const PDFHeader: React.FC<PDFHeaderProps> = ({ projectName, reportTitle, date }) => (
  <View style={styles.header}>
    <View style={styles.headerLeft}>
      <Text style={styles.logo}>SiteSync PM</Text>
      <Text style={styles.projectName}>{projectName}</Text>
    </View>
    <View style={styles.headerRight}>
      <Text style={styles.reportTitle}>{reportTitle}</Text>
      <Text style={styles.reportDate}>{date}</Text>
    </View>
  </View>
)

// Reusable footer
export const PDFFooter: React.FC = () => (
  <View style={styles.footer} fixed>
    <Text style={styles.footerText}>Generated by SiteSync PM</Text>
    <Text style={styles.footerText} render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
  </View>
)

// Reusable table
interface PDFTableProps {
  columns: Array<{ header: string; width: string; key: string }>
  rows: Array<Record<string, string>>
}

export const PDFTable: React.FC<PDFTableProps> = ({ columns, rows }) => (
  <View style={styles.table}>
    <View style={styles.tableHeader}>
      {columns.map((col) => (
        <Text key={col.key} style={[styles.tableHeaderCell, { width: col.width }]}>{col.header}</Text>
      ))}
    </View>
    {rows.map((row, i) => (
      <View key={i} style={i % 2 === 0 ? styles.tableRow : styles.tableRowAlt}>
        {columns.map((col) => (
          <Text key={col.key} style={[styles.tableCell, { width: col.width }]}>{row[col.key] || ''}</Text>
        ))}
      </View>
    ))}
  </View>
)

// Section title
export const PDFSection: React.FC<{ title: string }> = ({ title }) => (
  <Text style={styles.sectionTitle}>{title}</Text>
)

// Full report wrapper
interface PDFReportProps {
  projectName: string
  reportTitle: string
  children: React.ReactNode
}

export const PDFReport: React.FC<PDFReportProps> = ({ projectName, reportTitle, children }) => {
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <PDFHeader projectName={projectName} reportTitle={reportTitle} date={date} />
        {children}
        <PDFFooter />
      </Page>
    </Document>
  )
}

export { styles as pdfStyles }
