#!/usr/bin/env tsx
// CI gate: fails if the generated migration + edge mirror have drifted from
// what `npm run permissions:generate` would produce given the current
// src/permissions.ts. Run as part of test.yml.

import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import {
  ROLES,
  ROLE_HIERARCHY,
  PERMISSION_MATRIX,
  MODULE_PERMISSIONS,
  type Role,
  type Permission,
} from '../src/permissions'

const REPO_ROOT = join(import.meta.dirname, '..')
const SQL_PATH = join(REPO_ROOT, 'supabase/migrations/20260511000000_role_constraint_15_roles.sql')
const EDGE_PATH = join(REPO_ROOT, 'supabase/functions/shared/permissions.ts')

// Inline the same builders as generate-permissions-sql.ts. Duplicating them
// keeps the check self-contained (no shelling out, no temp dirs, no race with
// the generator). The two must stay byte-identical — if you edit one, edit
// both. Tested via the integration test below.

const HEADER = `-- AUTOGENERATED from src/permissions.ts by scripts/generate-permissions-sql.ts
-- DO NOT EDIT MANUALLY. Run \`npm run permissions:generate\` to regenerate.
-- Drift detector: \`npm run permissions:check\`.`

function buildSql(): string {
  const roleList = ROLES.map((r) => `'${r}'`).join(', ')
  const caseBranches = ROLES.map((r) => `    WHEN '${r}' THEN ${ROLE_HIERARCHY[r]}`).join('\n')

  return `${HEADER}

-- ── Expand project_members.role CHECK from 6 → 15 roles ──────
ALTER TABLE project_members DROP CONSTRAINT IF EXISTS project_members_role_check;
ALTER TABLE project_members ADD CONSTRAINT project_members_role_check
  CHECK (role IN (${roleList}));

-- ── has_project_permission: 15-role hierarchy ───────────────
-- Existing roles' relative ordering is preserved (owner > admin > project_manager
-- > superintendent > subcontractor > viewer), so existing RLS policies that call
-- this function return the same boolean. Numeric levels shift (owner: 6→7, admin:
-- 5→6, project_manager: 4→5, superintendent: 3→4) but no policy hard-codes them.
CREATE OR REPLACE FUNCTION has_project_permission(p_project_id uuid, p_min_role text)
RETURNS boolean AS $$
DECLARE
  user_role text;
  role_level int;
  min_level int;
BEGIN
  SELECT role INTO user_role FROM project_members
  WHERE project_id = p_project_id AND user_id = auth.uid();

  IF user_role IS NULL THEN RETURN false; END IF;

  role_level := CASE user_role
${caseBranches}
    ELSE 0
  END;

  min_level := CASE p_min_role
${caseBranches}
    ELSE 0
  END;

  RETURN role_level >= min_level;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER STABLE;
`
}

function buildEdgeMirror(): string {
  const rolesLiteral = ROLES.map((r) => `  '${r}',`).join('\n')
  const hierarchyEntries = ROLES.map((r) => `  ${r}: ${ROLE_HIERARCHY[r]},`).join('\n')

  const permissions = Object.keys(PERMISSION_MATRIX) as Permission[]
  const permissionUnion = permissions.map((p) => `  | '${p}'`).join('\n')
  const matrixEntries = permissions
    .map((p) => {
      const allowed = PERMISSION_MATRIX[p].map((r) => `'${r}'`).join(', ')
      return `  '${p}': [${allowed}],`
    })
    .join('\n')
  const moduleEntries = Object.entries(MODULE_PERMISSIONS)
    .map(([k, v]) => `  ${JSON.stringify(k)}: '${v}',`)
    .join('\n')

  return `// AUTOGENERATED from src/permissions.ts by scripts/generate-permissions-sql.ts
// DO NOT EDIT MANUALLY. Run \`npm run permissions:generate\` to regenerate.
// Drift detector: \`npm run permissions:check\`.
//
// Deno-compatible edge mirror. Edge functions (supabase/functions/*) import
// from here:
//   import { can, getAllowedActions } from '../shared/permissions.ts'

export const ROLES = [
${rolesLiteral}
] as const

export type Role = typeof ROLES[number]

export const ROLE_HIERARCHY: Record<Role, number> = {
${hierarchyEntries}
}

export type Permission =
${permissionUnion}

export const PERMISSION_MATRIX: Record<Permission, readonly Role[]> = {
${matrixEntries}
}

export const MODULE_PERMISSIONS: Record<string, Permission> = {
${moduleEntries}
}

export function can(role: Role | null | undefined, action: Permission): boolean {
  if (!role) return false
  const allowed = PERMISSION_MATRIX[action]
  return allowed ? allowed.includes(role) : false
}

export function canAny(role: Role | null | undefined, actions: Permission[]): boolean {
  return actions.some((a) => can(role, a))
}

export function isAtLeast(role: Role | null | undefined, minRole: Role): boolean {
  if (!role) return false
  return ROLE_HIERARCHY[role] >= ROLE_HIERARCHY[minRole]
}

export function getAllowedActions(role: Role | null | undefined): Permission[] {
  if (!role) return []
  return (Object.keys(PERMISSION_MATRIX) as Permission[]).filter((a) => can(role, a))
}
`
}

function main(): never {
  const expectedSql = buildSql()
  const expectedEdge = buildEdgeMirror()

  const errors: string[] = []

  if (!existsSync(SQL_PATH)) {
    errors.push(`Missing migration: ${SQL_PATH}\n  Run: npm run permissions:generate`)
  } else {
    const actualSql = readFileSync(SQL_PATH, 'utf8')
    if (actualSql !== expectedSql) {
      errors.push(
        `Migration drift detected: ${SQL_PATH}\n` +
          `  Run: npm run permissions:generate\n` +
          `  (src/permissions.ts and the migration disagree on ROLES or ROLE_HIERARCHY.)`,
      )
    }
  }

  if (!existsSync(EDGE_PATH)) {
    errors.push(`Missing edge mirror: ${EDGE_PATH}\n  Run: npm run permissions:generate`)
  } else {
    const actualEdge = readFileSync(EDGE_PATH, 'utf8')
    if (actualEdge !== expectedEdge) {
      errors.push(
        `Edge mirror drift detected: ${EDGE_PATH}\n` +
          `  Run: npm run permissions:generate\n` +
          `  (src/permissions.ts and the edge mirror disagree.)`,
      )
    }
  }

  if (errors.length > 0) {
    // eslint-disable-next-line no-console
    console.error('✗ permissions:check failed:\n')
    for (const err of errors) {
      // eslint-disable-next-line no-console
      console.error(err + '\n')
    }
    process.exit(1)
  }

  // eslint-disable-next-line no-console
  console.log('✓ permissions in sync — SQL migration + edge mirror match src/permissions.ts')
  process.exit(0)
}

// Anchor the Role type so it isn't tree-shaken from the strict-noUnusedLocals
// build. This file's job is to be re-runnable and self-validating.
type _Anchor = Role

main()
