#!/usr/bin/env python3
"""
filter-adversarial-tests.py

Filters adversarial test files generated by the self-play workflow.
Runs each test file N times and keeps only consistent tests:
  - CONSISTENT PASS (passes all N runs) → keep as regression guard
  - CONSISTENT FAIL (fails all N runs)  → keep as proven bug probe
  - FLAKY (mixed results across runs)   → remove; unreliable signal

Usage:
    python scripts/filter-adversarial-tests.py \\
        --test-dir src/test/adversarial/ \\
        --runs 3 \\
        --output src/test/adversarial/filter-summary.json

Exit codes:
    0  Filter completed successfully
    1  Argument error or test runner not found
    2  Test directory does not exist or contains no test files
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


# ─────────────────────────────────────────────────────────────────────────────
# Constants
# ─────────────────────────────────────────────────────────────────────────────

ADVERSARIAL_TEST_GLOB = "*.adversarial.test.ts"
SKIP_FILES = {
    "manifest.json",
    "verification-report.json",
    "filter-summary.json",
}


# ─────────────────────────────────────────────────────────────────────────────
# Test runner
# ─────────────────────────────────────────────────────────────────────────────

def run_single_test(test_file: Path, timeout_seconds: int = 60) -> bool:
    """
    Run a single Vitest test file once.

    Args:
        test_file: Absolute or relative path to the .test.ts file.
        timeout_seconds: Maximum seconds to wait before treating as a failure.

    Returns:
        True if the test run passed (exit code 0), False otherwise.
    """
    try:
        result = subprocess.run(
            ["npx", "vitest", "run", str(test_file), "--reporter=verbose"],
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
        )
        return result.returncode == 0
    except subprocess.TimeoutExpired:
        print(
            f"  [filter] TIMEOUT: {test_file.name} exceeded {timeout_seconds}s",
            file=sys.stderr,
        )
        return False
    except FileNotFoundError:
        print(
            "[filter] ERROR: 'npx' not found. Is Node.js installed?",
            file=sys.stderr,
        )
        sys.exit(1)
    except OSError as e:
        print(f"  [filter] OS error running {test_file.name}: {e}", file=sys.stderr)
        return False


def run_test_n_times(test_file: Path, n: int) -> list[bool]:
    """
    Run a test file N times sequentially.

    Args:
        test_file: Path to the test file.
        n: Number of times to run.

    Returns:
        List of N booleans (True = pass, False = fail) in run order.
    """
    results: list[bool] = []
    for i in range(1, n + 1):
        passed = run_single_test(test_file)
        status = "PASS" if passed else "FAIL"
        print(f"    run {i}/{n}: {status}")
        results.append(passed)
    return results


# ─────────────────────────────────────────────────────────────────────────────
# Classification
# ─────────────────────────────────────────────────────────────────────────────

def classify(results: list[bool]) -> str:
    """
    Classify a test based on its run results.

    Args:
        results: List of pass/fail booleans from repeated runs.

    Returns:
        "consistent_pass" | "consistent_fail" | "flaky"
    """
    if all(results):
        return "consistent_pass"
    if not any(results):
        return "consistent_fail"
    return "flaky"


# ─────────────────────────────────────────────────────────────────────────────
# File operations
# ─────────────────────────────────────────────────────────────────────────────

def delete_test_file(test_file: Path) -> None:
    """
    Delete a flaky test file.

    Args:
        test_file: Path to the file to delete.
    """
    try:
        test_file.unlink()
        print(f"  [filter] Deleted flaky test: {test_file.name}")
    except FileNotFoundError:
        pass  # Already gone — that's fine
    except PermissionError as e:
        print(
            f"  [filter] WARNING: Could not delete {test_file.name}: {e}",
            file=sys.stderr,
        )


def annotate_test_file(test_file: Path, classification: str) -> None:
    """
    Prepend a filter-status comment to the test file.

    Args:
        test_file: Path to the test file.
        classification: "consistent_pass" or "consistent_fail".
    """
    label_map = {
        "consistent_pass": "CONSISTENT PASS — kept as regression guard",
        "consistent_fail": "CONSISTENT FAIL — kept as proven bug probe; do not fix here",
    }
    label = label_map.get(classification, classification)

    try:
        original = test_file.read_text(encoding="utf-8")
        # Avoid double-annotating if the script is run multiple times
        if "// FILTER STATUS:" in original:
            return
        annotated = f"// FILTER STATUS: {label}\n" + original
        test_file.write_text(annotated, encoding="utf-8")
    except (OSError, UnicodeDecodeError) as e:
        print(
            f"  [filter] WARNING: Could not annotate {test_file.name}: {e}",
            file=sys.stderr,
        )


# ─────────────────────────────────────────────────────────────────────────────
# Main pipeline
# ─────────────────────────────────────────────────────────────────────────────

def filter_adversarial_tests(
    test_dir: Path,
    n_runs: int,
    output_path: Path,
) -> dict:
    """
    Run the full filter pipeline on all adversarial test files in test_dir.

    Args:
        test_dir: Directory containing *.adversarial.test.ts files.
        n_runs: Number of times to run each test.
        output_path: Where to write the JSON summary.

    Returns:
        Summary dict with kept/removed lists and per-file details.
    """
    test_files = sorted(
        f for f in test_dir.glob(ADVERSARIAL_TEST_GLOB)
        if f.name not in SKIP_FILES
    )

    if not test_files:
        print(
            f"[filter] No adversarial test files found in {test_dir}",
            file=sys.stderr,
        )
        sys.exit(2)

    print(f"[filter] Found {len(test_files)} test file(s). Running each {n_runs} time(s).\n")

    kept: list[str] = []
    removed_flaky: list[str] = []
    details: list[dict] = []

    for test_file in test_files:
        print(f"  Testing: {test_file.name}")
        run_results = run_test_n_times(test_file, n_runs)
        classification = classify(run_results)

        detail: dict = {
            "file": str(test_file.relative_to(test_dir.parent.parent)
                        if test_dir.parent.parent.exists()
                        else test_file),
            "classification": classification,
            "runs": [{"run": i + 1, "passed": r} for i, r in enumerate(run_results)],
        }

        if classification == "flaky":
            pass_count = sum(run_results)
            fail_count = n_runs - pass_count
            detail["note"] = f"Flaky: {pass_count} pass, {fail_count} fail across {n_runs} runs"
            print(f"    → FLAKY ({pass_count}/{n_runs} pass) — removing")
            removed_flaky.append(test_file.name)
            delete_test_file(test_file)
        else:
            if classification == "consistent_pass":
                print(f"    → CONSISTENT PASS — keeping as regression guard")
            else:
                print(f"    → CONSISTENT FAIL — keeping as proven bug probe")
            kept.append(test_file.name)
            annotate_test_file(test_file, classification)

        details.append(detail)
        print()

    summary = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "test_dir": str(test_dir),
        "n_runs": n_runs,
        "total_generated": len(test_files),
        "kept": kept,
        "removed_flaky": removed_flaky,
        "stats": {
            "kept_count": len(kept),
            "removed_flaky_count": len(removed_flaky),
            "consistent_pass": sum(
                1 for d in details if d["classification"] == "consistent_pass"
            ),
            "consistent_fail": sum(
                1 for d in details if d["classification"] == "consistent_fail"
            ),
        },
        "details": details,
    }

    # Write summary
    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(
            json.dumps(summary, indent=2) + "\n",
            encoding="utf-8",
        )
        print(f"[filter] Summary written to {output_path}")
    except OSError as e:
        print(f"[filter] ERROR: Could not write summary: {e}", file=sys.stderr)
        sys.exit(1)

    return summary


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────

def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--test-dir",
        required=True,
        type=Path,
        metavar="DIR",
        help="Directory containing *.adversarial.test.ts files",
    )
    parser.add_argument(
        "--runs",
        type=int,
        default=3,
        metavar="N",
        help="Number of times to run each test (default: 3)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        metavar="FILE",
        help="Path for the JSON summary output (default: <test-dir>/filter-summary.json)",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)

    test_dir = args.test_dir.resolve()
    if not test_dir.exists():
        print(f"[filter] ERROR: Test directory not found: {test_dir}", file=sys.stderr)
        sys.exit(2)

    output_path = args.output or (test_dir / "filter-summary.json")

    summary = filter_adversarial_tests(
        test_dir=test_dir,
        n_runs=args.runs,
        output_path=output_path,
    )

    # Print final summary to stdout
    stats = summary["stats"]
    print("─" * 60)
    print(f"Filter complete")
    print(f"  Total generated : {summary['total_generated']}")
    print(f"  Kept (consistent): {stats['kept_count']}")
    print(f"    Consistent pass: {stats['consistent_pass']}")
    print(f"    Consistent fail: {stats['consistent_fail']} (proven bugs)")
    print(f"  Removed (flaky) : {stats['removed_flaky_count']}")
    print("─" * 60)

    if stats["consistent_fail"] > 0:
        print(
            f"\n{stats['consistent_fail']} test(s) are consistently failing — "
            "real bugs detected. See filter-summary.json for details."
        )


# ─────────────────────────────────────────────────────────────────────────────
# Self-test (run via: python filter-adversarial-tests.py)
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    # If invoked with no arguments, run the self-test
    if len(sys.argv) == 1:
        print("[self-test] Testing classify() logic...")

        assert classify([True, True, True]) == "consistent_pass", "all pass → consistent_pass"
        assert classify([False, False, False]) == "consistent_fail", "all fail → consistent_fail"
        assert classify([True, False, True]) == "flaky", "mixed → flaky"
        assert classify([True, True, False]) == "flaky", "mixed → flaky"
        assert classify([False, True, False]) == "flaky", "mixed → flaky"

        print("[self-test] classify() — all assertions passed.")
        print("[self-test] Self-test complete. Exit 0.")
        sys.exit(0)

    main()
