// Reads PAGE_REGISTRY and emits one Playwright spec per creatable entity,
// wiring in fixtures from audit/fixtures.ts. The output file is gitignored.
//
// Locator strategy: looks for a button with data-testid="create-<entity>-button"
// added in a separate fix pass. Until every Create button has a testid, the
// generated spec is allowed to fail gracefully — it's informational during
// the backfill.
//
//   npm run audit:gen

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { PAGE_REGISTRY } from '../audit/registry'
import { CREATE_FIXTURES } from '../audit/fixtures'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const REPO_ROOT = path.resolve(__dirname, '..')

const OUT_DIR = path.join(REPO_ROOT, 'audit', 'generated')
const OUT_FILE = path.join(OUT_DIR, 'entity-crud.spec.ts')

function toFixtureSource(entity: string): string {
  const fills = CREATE_FIXTURES[entity as keyof typeof CREATE_FIXTURES] ?? []
  if (fills.length === 0) return '    // no fixture — entity has no required fields declared\n'
  return fills
    .map(
      (f) =>
        `    await fillByLabel(page, ${f.label.toString()}, ${JSON.stringify(f.value)});`,
    )
    .join('\n')
}

const header = `// AUTO-GENERATED by scripts/generate-e2e.ts — do not edit by hand.
// Regenerate with \`npm run audit:gen\`.
//
// Assumes a Create button with data-testid="create-<entity>-button" is rendered
// on each list page. Entities where testids are still missing will fail — that's
// intentional, it surfaces the fix work in the Playwright report.

import { test, expect, type Page } from '@playwright/test'

async function fillByLabel(page: Page, labelRe: RegExp, value: string): Promise<void> {
  const field = page.getByLabel(labelRe).first()
  if (!(await field.count())) return
  const tag = await field.evaluate((el) => el.tagName.toLowerCase())
  if (tag === 'select') {
    await field.selectOption({ label: value }).catch(() => field.selectOption(value))
  } else {
    await field.fill(value)
  }
}
`

function generate(): string {
  const blocks: string[] = [header]
  for (const contract of PAGE_REGISTRY) {
    if (!contract.entity) continue
    if (!contract.expected.has_create) continue
    if (contract.status === 'stub') continue
    const testName = `${contract.entity} create → appears in list`
    blocks.push(
      `
test(${JSON.stringify(testName)}, async ({ page }) => {
  await page.goto('/#${contract.route}')
  await page.waitForSelector('[role="main"], main', { timeout: 10_000 })

  const trigger = page.getByTestId('create-${contract.entity}-button').first()
  await expect(trigger, 'Create button missing data-testid="create-${contract.entity}-button"').toBeVisible({ timeout: 5_000 })
  await trigger.click()

  const modal = page.getByRole('dialog').first()
  await expect(modal).toBeVisible({ timeout: 5_000 })

${toFixtureSource(contract.entity)}

  const submit = modal.getByRole('button', { name: /create|save|submit|add/i }).first()
  await submit.click()

  await expect(page.getByText(/created|success|saved|added/i).first()).toBeVisible({ timeout: 10_000 })
})`,
    )
  }
  return blocks.join('\n')
}

function main(): void {
  fs.mkdirSync(OUT_DIR, { recursive: true })
  const content = generate()
  fs.writeFileSync(OUT_FILE, content, 'utf8')
  // eslint-disable-next-line no-console
  console.log(`Generated ${OUT_FILE.replace(REPO_ROOT + '/', '')}`)
}

main()
