/**
 * generate-doc-index.ts
 *
 * Walks src/lib/, src/services/, supabase/functions/, supabase/migrations/
 * and emits a markdown index. Each entry is the file path + the first
 * comment block from the file (JSDoc-style or single-line) as description.
 *
 * The output is intended to be inlined into docs/README.md between
 * <!-- AUTO:engineering-reference:start --> and <!-- AUTO:engineering-reference:end --> markers.
 *
 * Run: npx tsx scripts/generate-doc-index.ts > /tmp/index.md
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const REPO_ROOT = path.resolve(__dirname, "..");
const ROOTS = [
  "src/lib",
  "src/services",
  "supabase/functions",
  "supabase/migrations",
];

interface Entry {
  relPath: string;
  description: string;
}

function listFiles(rootRel: string, exts: string[]): string[] {
  const root = path.join(REPO_ROOT, rootRel);
  const out: string[] = [];
  function walk(dir: string) {
    if (!fs.existsSync(dir)) return;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (entry.name === "node_modules" || entry.name === "__tests__") continue;
        walk(full);
      } else if (entry.isFile()) {
        for (const ext of exts) {
          if (entry.name.endsWith(ext)) {
            out.push(full);
            break;
          }
        }
      }
    }
  }
  walk(root);
  return out;
}

function firstCommentBlock(text: string): string {
  // JSDoc-style /** ... */ at top
  const jsdoc = text.match(/^\s*\/\*\*([\s\S]*?)\*\//);
  if (jsdoc) {
    return jsdoc[1]
      .split("\n")
      .map((line) => line.replace(/^\s*\*\s?/, "").trim())
      .filter((line) => line.length > 0)
      .join(" ")
      .slice(0, 240);
  }
  // SQL/JS line comments: leading -- or //
  const lines = text.split("\n");
  const collected: string[] = [];
  for (const line of lines) {
    const m = line.match(/^\s*(?:--|\/\/)\s?(.*)$/);
    if (m && m[1].trim()) {
      collected.push(m[1].trim());
    } else if (collected.length > 0 || line.trim() === "") {
      if (collected.length > 0) break;
    } else {
      break;
    }
  }
  if (collected.length > 0) return collected.join(" ").slice(0, 240);
  return "";
}

function entriesFor(rootRel: string, exts: string[]): Entry[] {
  const files = listFiles(rootRel, exts);
  files.sort();
  const out: Entry[] = [];
  for (const f of files) {
    const text = fs.readFileSync(f, "utf8");
    const description = firstCommentBlock(text);
    out.push({
      relPath: path.relative(REPO_ROOT, f),
      description,
    });
  }
  return out;
}

function emitSection(title: string, entries: Entry[]): string {
  const lines: string[] = [];
  lines.push(`### ${title}`);
  lines.push("");
  if (entries.length === 0) {
    lines.push("_(none)_");
    lines.push("");
    return lines.join("\n");
  }
  for (const e of entries) {
    if (e.description) {
      lines.push(`- \`${e.relPath}\` — ${e.description}`);
    } else {
      lines.push(`- \`${e.relPath}\``);
    }
  }
  lines.push("");
  return lines.join("\n");
}

function main() {
  const sections: Array<[string, string, string[]]> = [
    ["Pure libraries (`src/lib/`)", "src/lib", [".ts", ".tsx"]],
    ["Services (`src/services/`)", "src/services", [".ts"]],
    ["Edge functions (`supabase/functions/`)", "supabase/functions", [".ts"]],
    ["Migrations (`supabase/migrations/`)", "supabase/migrations", [".sql"]],
  ];

  const out: string[] = [];
  out.push(`<!-- generated by scripts/generate-doc-index.ts -->`);
  out.push("");
  for (const [title, root, exts] of sections) {
    const entries = entriesFor(root, exts);
    out.push(emitSection(title, entries));
  }
  process.stdout.write(out.join("\n"));
}

main();
