#!/usr/bin/env tsx
// Generates the role-permission DB migration + edge mirror from src/permissions.ts.
//
// Outputs:
//   1. supabase/migrations/20260511000000_role_constraint_15_roles.sql
//      — drops the legacy 6-role CHECK on project_members.role and replaces it
//        with the 15-role list from permissions.ts. Rewrites
//        has_project_permission() with the matching hierarchy.
//   2. supabase/functions/shared/permissions.ts
//      — Deno-compatible mirror containing ROLES, Role, ROLE_HIERARCHY,
//        PERMISSION_MATRIX, can(), canAny(), isAtLeast(), getAllowedActions().
//        Edge functions (agent-runner, iris-ground) import from here.
//
// Run: `npm run permissions:generate`
// Drift CI:   `npm run permissions:check`
//
// Why generate the SQL: Postgres has no native way to enforce that the CHECK
// constraint matches a TS enum. The codegen + sync-check makes the drift
// impossible without a CI failure.

import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import {
  ROLES,
  ROLE_HIERARCHY,
  PERMISSION_MATRIX,
  MODULE_PERMISSIONS,
  type Role,
  type Permission,
} from '../src/permissions'

const REPO_ROOT = join(import.meta.dirname, '..')
const SQL_PATH = join(REPO_ROOT, 'supabase/migrations/20260511000000_role_constraint_15_roles.sql')
const EDGE_PATH = join(REPO_ROOT, 'supabase/functions/shared/permissions.ts')

const HEADER = `-- AUTOGENERATED from src/permissions.ts by scripts/generate-permissions-sql.ts
-- DO NOT EDIT MANUALLY. Run \`npm run permissions:generate\` to regenerate.
-- Drift detector: \`npm run permissions:check\`.`

function buildSql(): string {
  const roleList = ROLES.map((r) => `'${r}'`).join(', ')
  const caseBranches = ROLES.map((r) => `    WHEN '${r}' THEN ${ROLE_HIERARCHY[r]}`).join('\n')

  return `${HEADER}

-- ── Expand project_members.role CHECK from 6 → 15 roles ──────
ALTER TABLE project_members DROP CONSTRAINT IF EXISTS project_members_role_check;
ALTER TABLE project_members ADD CONSTRAINT project_members_role_check
  CHECK (role IN (${roleList}));

-- ── has_project_permission: 15-role hierarchy ───────────────
-- Existing roles' relative ordering is preserved (owner > admin > project_manager
-- > superintendent > subcontractor > viewer), so existing RLS policies that call
-- this function return the same boolean. Numeric levels shift (owner: 6→7, admin:
-- 5→6, project_manager: 4→5, superintendent: 3→4) but no policy hard-codes them.
CREATE OR REPLACE FUNCTION has_project_permission(p_project_id uuid, p_min_role text)
RETURNS boolean AS $$
DECLARE
  user_role text;
  role_level int;
  min_level int;
BEGIN
  SELECT role INTO user_role FROM project_members
  WHERE project_id = p_project_id AND user_id = auth.uid();

  IF user_role IS NULL THEN RETURN false; END IF;

  role_level := CASE user_role
${caseBranches}
    ELSE 0
  END;

  min_level := CASE p_min_role
${caseBranches}
    ELSE 0
  END;

  RETURN role_level >= min_level;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER STABLE;
`
}

function buildEdgeMirror(): string {
  const rolesLiteral = ROLES.map((r) => `  '${r}',`).join('\n')

  const hierarchyEntries = ROLES.map((r) => `  ${r}: ${ROLE_HIERARCHY[r]},`).join('\n')

  const permissions = Object.keys(PERMISSION_MATRIX) as Permission[]
  const permissionUnion = permissions.map((p) => `  | '${p}'`).join('\n')
  const matrixEntries = permissions
    .map((p) => {
      const allowed = PERMISSION_MATRIX[p].map((r) => `'${r}'`).join(', ')
      return `  '${p}': [${allowed}],`
    })
    .join('\n')

  const moduleEntries = Object.entries(MODULE_PERMISSIONS)
    .map(([k, v]) => `  ${JSON.stringify(k)}: '${v}',`)
    .join('\n')

  return `// AUTOGENERATED from src/permissions.ts by scripts/generate-permissions-sql.ts
// DO NOT EDIT MANUALLY. Run \`npm run permissions:generate\` to regenerate.
// Drift detector: \`npm run permissions:check\`.
//
// Deno-compatible edge mirror. Edge functions (supabase/functions/*) import
// from here:
//   import { can, getAllowedActions } from '../shared/permissions.ts'

export const ROLES = [
${rolesLiteral}
] as const

export type Role = typeof ROLES[number]

export const ROLE_HIERARCHY: Record<Role, number> = {
${hierarchyEntries}
}

export type Permission =
${permissionUnion}

export const PERMISSION_MATRIX: Record<Permission, readonly Role[]> = {
${matrixEntries}
}

export const MODULE_PERMISSIONS: Record<string, Permission> = {
${moduleEntries}
}

export function can(role: Role | null | undefined, action: Permission): boolean {
  if (!role) return false
  const allowed = PERMISSION_MATRIX[action]
  return allowed ? allowed.includes(role) : false
}

export function canAny(role: Role | null | undefined, actions: Permission[]): boolean {
  return actions.some((a) => can(role, a))
}

export function isAtLeast(role: Role | null | undefined, minRole: Role): boolean {
  if (!role) return false
  return ROLE_HIERARCHY[role] >= ROLE_HIERARCHY[minRole]
}

export function getAllowedActions(role: Role | null | undefined): Permission[] {
  if (!role) return []
  return (Object.keys(PERMISSION_MATRIX) as Permission[]).filter((a) => can(role, a))
}
`
}

function main() {
  const sql = buildSql()
  const edge = buildEdgeMirror()

  writeFileSync(SQL_PATH, sql, 'utf8')
  writeFileSync(EDGE_PATH, edge, 'utf8')

  // Sanity: report sizes.
  // eslint-disable-next-line no-console
  console.log(`✓ wrote ${SQL_PATH} (${sql.length} bytes)`)
  // eslint-disable-next-line no-console
  console.log(`✓ wrote ${EDGE_PATH} (${edge.length} bytes)`)
  // eslint-disable-next-line no-console
  console.log(`  ROLES: ${ROLES.length}, PERMISSION_MATRIX rows: ${Object.keys(PERMISSION_MATRIX).length}`)
}

// Suppress unused-type warning when the file is imported as a module.
export type { Role as _R, Permission as _P }

main()
