// Emits two artifacts from an AuditReport:
//   audit/PAGE_HEALTH.json  — machine-readable, consumed by CI diffs
//   audit/PAGE_HEALTH.md    — human-readable, scannable in PRs

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import type { AuditReport, AuditResult, Severity } from './types'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const REPO_ROOT = path.resolve(__dirname, '..', '..')
const MD_PATH = path.join(REPO_ROOT, 'audit', 'PAGE_HEALTH.md')
const JSON_PATH = path.join(REPO_ROOT, 'audit', 'PAGE_HEALTH.json')

function tick(present: boolean | undefined, declared: boolean | undefined): string {
  if (!declared) return '—'
  return present ? '✅' : '❌'
}

function topIssue(result: AuditResult): string {
  const severityOrder: Severity[] = ['P0', 'P1', 'P2', 'P3']
  for (const sev of severityOrder) {
    const f = result.findings.find((x) => x.severity === sev)
    if (f) return `${f.severity}: ${f.message}`
  }
  if (result.contract.knownIssues?.length) return result.contract.knownIssues[0]
  return ''
}

function scoreCell(result: AuditResult): string {
  if (result.score < 0) return 'stub'
  return `${result.score}%`
}

function renderMarkdown(report: AuditReport): string {
  const lines: string[] = []
  lines.push('# Page Health Report')
  lines.push('')
  lines.push(`_Generated: ${report.generatedAt}_`)
  lines.push('')
  lines.push(
    `**${report.passingRoutes} of ${report.totalRoutes}** routes at 100%. Average score: **${report.averageScore}%**.`,
  )
  lines.push('')
  lines.push(
    '> This file is regenerated by `npm run audit:static`. Do not edit manually. Entries are derived from `audit/registry.ts`.',
  )
  lines.push('')

  // Global findings (registry drift, missing files)
  if (report.globalFindings.length > 0) {
    lines.push('## Registry drift / missing files')
    lines.push('')
    for (const f of report.globalFindings) {
      lines.push(`- **${f.severity}** \`${f.code}\`: ${f.message}`)
    }
    lines.push('')
  }

  // Main table
  lines.push('## Per-route status')
  lines.push('')
  lines.push(
    '| Route | Entity | List | Create | Edit | Delete | Import | Export | Detail | Score | Top Issue |',
  )
  lines.push(
    '|---|---|:-:|:-:|:-:|:-:|:-:|:-:|:-:|--:|---|',
  )
  for (const r of report.results) {
    const c = r.contract
    lines.push(
      [
        `| \`${c.route}\``,
        c.entity ?? '—',
        tick(r.actual.has_list, c.expected.has_list),
        tick(r.actual.has_create, c.expected.has_create),
        tick(r.actual.has_edit, c.expected.has_edit),
        tick(r.actual.has_delete, c.expected.has_delete),
        tick(r.actual.has_import, c.expected.has_import),
        tick(r.actual.has_export, c.expected.has_export),
        tick(r.actual.has_detail_view, c.expected.has_detail_view),
        scoreCell(r),
        topIssue(r),
        '|',
      ].join(' | '),
    )
  }
  lines.push('')

  // Prioritized fixes
  const buckets: Record<Severity, string[]> = { P0: [], P1: [], P2: [], P3: [] }
  for (const r of report.results) {
    for (const f of r.findings) {
      buckets[f.severity].push(`- \`${r.contract.route}\` (${f.code}): ${f.message}`)
    }
  }
  for (const f of report.globalFindings) {
    buckets[f.severity].push(`- **registry** (${f.code}): ${f.message}`)
  }

  lines.push('## Prioritized fixes')
  lines.push('')
  for (const sev of ['P0', 'P1', 'P2', 'P3'] as Severity[]) {
    if (buckets[sev].length === 0) continue
    lines.push(`### ${sev} — ${buckets[sev].length} finding${buckets[sev].length === 1 ? '' : 's'}`)
    lines.push('')
    for (const line of buckets[sev]) lines.push(line)
    lines.push('')
  }

  // Stubs
  const stubs = report.results.filter((r) => r.contract.status === 'stub')
  if (stubs.length > 0) {
    lines.push('## Stub pages (tracked, not counted)')
    lines.push('')
    for (const s of stubs) {
      const issues = s.contract.knownIssues?.join('; ') ?? ''
      lines.push(`- \`${s.contract.route}\` — ${s.contract.title}${issues ? ` (${issues})` : ''}`)
    }
    lines.push('')
  }

  return lines.join('\n')
}

export function writeReport(report: AuditReport): { mdPath: string; jsonPath: string } {
  fs.mkdirSync(path.dirname(MD_PATH), { recursive: true })
  fs.writeFileSync(MD_PATH, renderMarkdown(report), 'utf8')
  fs.writeFileSync(JSON_PATH, JSON.stringify(report, null, 2), 'utf8')
  return { mdPath: MD_PATH, jsonPath: JSON_PATH }
}
