-- AUTOGENERATED from src/permissions.ts by scripts/generate-permissions-sql.ts
-- DO NOT EDIT MANUALLY. Run `npm run permissions:generate` to regenerate.
-- Drift detector: `npm run permissions:check`.

-- ── Expand project_members.role CHECK from 6 → 15 roles ──────
ALTER TABLE project_members DROP CONSTRAINT IF EXISTS project_members_role_check;
ALTER TABLE project_members ADD CONSTRAINT project_members_role_check
  CHECK (role IN ('owner', 'project_executive', 'admin', 'project_manager', 'superintendent', 'foreman', 'project_engineer', 'field_engineer', 'safety_manager', 'subcontractor', 'architect', 'owner_rep', 'member', 'field_user', 'viewer'));

-- ── has_project_permission: 15-role hierarchy ───────────────
-- Existing roles' relative ordering is preserved (owner > admin > project_manager
-- > superintendent > subcontractor > viewer), so existing RLS policies that call
-- this function return the same boolean. Numeric levels shift (owner: 6→7, admin:
-- 5→6, project_manager: 4→5, superintendent: 3→4) but no policy hard-codes them.
--
-- BEHAVIOR NOTE: roles previously absent from the CASE (foreman, project_engineer,
-- field_engineer, safety_manager, project_executive, architect, owner_rep, member,
-- field_user) used to fall through to `ELSE 0`, making any policy that passed
-- one of them as p_min_role a no-op (always returned true since every authenticated
-- role had role_level >= 1). They now have explicit hierarchy levels. The most
-- visible side effect: equipment service policies in
-- 20260417000008_equipment_service_layer.sql at lines 128/134/192 pass 'foreman'
-- as p_min_role; the gate now correctly enforces level-3+ access. Roles at level 2
-- (subcontractor, architect, owner_rep, member, field_user) lose equipment write
-- access — restoring the policy author's original intent.
CREATE OR REPLACE FUNCTION has_project_permission(p_project_id uuid, p_min_role text)
RETURNS boolean AS $$
DECLARE
  user_role text;
  role_level int;
  min_level int;
BEGIN
  SELECT role INTO user_role FROM project_members
  WHERE project_id = p_project_id AND user_id = auth.uid();

  IF user_role IS NULL THEN RETURN false; END IF;

  role_level := CASE user_role
    WHEN 'owner' THEN 7
    WHEN 'project_executive' THEN 7
    WHEN 'admin' THEN 6
    WHEN 'project_manager' THEN 5
    WHEN 'superintendent' THEN 4
    WHEN 'foreman' THEN 3
    WHEN 'project_engineer' THEN 3
    WHEN 'field_engineer' THEN 3
    WHEN 'safety_manager' THEN 3
    WHEN 'subcontractor' THEN 2
    WHEN 'architect' THEN 2
    WHEN 'owner_rep' THEN 2
    WHEN 'member' THEN 2
    WHEN 'field_user' THEN 2
    WHEN 'viewer' THEN 1
    ELSE 0
  END;

  min_level := CASE p_min_role
    WHEN 'owner' THEN 7
    WHEN 'project_executive' THEN 7
    WHEN 'admin' THEN 6
    WHEN 'project_manager' THEN 5
    WHEN 'superintendent' THEN 4
    WHEN 'foreman' THEN 3
    WHEN 'project_engineer' THEN 3
    WHEN 'field_engineer' THEN 3
    WHEN 'safety_manager' THEN 3
    WHEN 'subcontractor' THEN 2
    WHEN 'architect' THEN 2
    WHEN 'owner_rep' THEN 2
    WHEN 'member' THEN 2
    WHEN 'field_user' THEN 2
    WHEN 'viewer' THEN 1
    ELSE 0
  END;

  RETURN role_level >= min_level;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER STABLE;
