/**
 * BRT sub-8 §4.4 scale test.
 *
 * DO NOT EXECUTE without Walker greenlight on staging spend —
 * Supabase reads at 50 VUs × 200/min = 10,000 req/min = 8.6M req/14hr = $X.
 *
 * Also accounts for:
 *   - 50 RFI creates  × 50 VUs = 2,500/min   (write quota)
 *   - 30 daily-log creates × 50 VUs = 1,500/min
 *   - 100 AI calls × 50 VUs = 5,000/min      (IRIS / Anthropic cost: this is the killer line)
 *   - 20 schedule reads × 50 VUs = 1,000/min
 *   - 10 PDF exports × 50 VUs = 500/min      (Edge function CPU-time spend)
 *
 * Spike phase (150 VUs × 5m) triples all numbers above for 5 minutes.
 *
 * --- USAGE ---
 *   k6 run \
 *     -e SUPABASE_URL=https://<staging>.supabase.co \
 *     -e SUPABASE_ANON_KEY=<anon> \
 *     -e TEST_ORG_IDS=<uuid>,<uuid>,...,<uuid> \
 *     scripts/scale-test/run.ts
 *
 * Required env:
 *   SUPABASE_URL        - staging project URL
 *   SUPABASE_ANON_KEY   - anon key (RLS-respecting)
 *   TEST_ORG_IDS        - comma-separated org UUIDs from seed-orgs.ts
 *
 * Generated by seed-orgs.ts. Tear down with:
 *   DELETE FROM organizations WHERE settings->>'scale_test' = 'true';
 *
 * Owner: BRT Track C / sub-8 §4.4
 */

// @ts-expect-error - k6 imports resolved at runtime by the k6 binary, not tsc.
import http from 'k6/http';
// @ts-expect-error - k6 imports resolved at runtime by the k6 binary, not tsc.
import { check, sleep } from 'k6';

// ---------------------------------------------------------------------------
// Load profile
// ---------------------------------------------------------------------------
//   1m  ramp-up   0  -> 50  VUs
//  30m  steady    50         VUs
//   5m  spike     50 -> 150  VUs (sustained)
//   1m  ramp-down 150 -> 0   VUs
// ---------------------------------------------------------------------------
export const options = {
  stages: [
    { duration: '1m', target: 50 },
    { duration: '30m', target: 50 },
    { duration: '5m', target: 150 },
    { duration: '1m', target: 0 },
  ],
  thresholds: {
    http_req_failed: ['rate<0.01'],
    http_req_duration: ['p(95)<500'],
    'checks{op:rfi_read}': ['rate>0.99'],
    'checks{op:rfi_create}': ['rate>0.99'],
    'checks{op:daily_log_create}': ['rate>0.99'],
    'checks{op:ai_call}': ['rate>0.95'], // AI is allowed slightly lower SLO
    'checks{op:schedule_read}': ['rate>0.99'],
    'checks{op:pdf_export}': ['rate>0.95'],
  },
};

// ---------------------------------------------------------------------------
// Env
// ---------------------------------------------------------------------------
const SUPABASE_URL = __ENV.SUPABASE_URL;
const SUPABASE_ANON_KEY = __ENV.SUPABASE_ANON_KEY;
const TEST_ORG_IDS = (__ENV.TEST_ORG_IDS || '')
  .split(',')
  .map((s: string) => s.trim())
  .filter(Boolean);

if (!SUPABASE_URL || !SUPABASE_ANON_KEY || TEST_ORG_IDS.length === 0) {
  throw new Error(
    'Missing required env: SUPABASE_URL, SUPABASE_ANON_KEY, TEST_ORG_IDS (comma-separated UUIDs)',
  );
}

const baseHeaders = {
  apikey: SUPABASE_ANON_KEY,
  Authorization: `Bearer ${SUPABASE_ANON_KEY}`,
  'Content-Type': 'application/json',
  Prefer: 'return=minimal',
};

// ---------------------------------------------------------------------------
// Per-VU per-minute call mix
// ---------------------------------------------------------------------------
// 200 RFI reads + 50 RFI creates + 30 daily-log creates +
// 100 AI calls + 20 schedule reads + 10 PDF exports = 410 calls/min/VU.
// ---------------------------------------------------------------------------
const CALLS_PER_MINUTE_PER_VU = 410;
const SLEEP_BETWEEN_CALLS_SEC = 60 / CALLS_PER_MINUTE_PER_VU;

type Op =
  | 'rfi_read'
  | 'rfi_create'
  | 'daily_log_create'
  | 'ai_call'
  | 'schedule_read'
  | 'pdf_export';

// Weighted bag of operations: each entry repeated by its target count.
const OP_BAG: Op[] = [
  ...Array<Op>(200).fill('rfi_read'),
  ...Array<Op>(50).fill('rfi_create'),
  ...Array<Op>(30).fill('daily_log_create'),
  ...Array<Op>(100).fill('ai_call'),
  ...Array<Op>(20).fill('schedule_read'),
  ...Array<Op>(10).fill('pdf_export'),
];

function pickOrg(): string {
  return TEST_ORG_IDS[Math.floor(Math.random() * TEST_ORG_IDS.length)];
}

function pickOp(): Op {
  return OP_BAG[Math.floor(Math.random() * OP_BAG.length)];
}

// ---------------------------------------------------------------------------
// Operation implementations
// ---------------------------------------------------------------------------

function rfiRead(orgId: string) {
  const res = http.get(
    `${SUPABASE_URL}/rest/v1/rfis?select=*&organization_id=eq.${orgId}`,
    { headers: baseHeaders, tags: { op: 'rfi_read' } },
  );
  check(
    res,
    { 'rfi_read status 200': (r: { status: number }) => r.status === 200 },
    { op: 'rfi_read' },
  );
}

function rfiCreate(orgId: string) {
  const body = JSON.stringify({
    organization_id: orgId,
    subject: `Scale-test RFI ${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    question: 'Synthetic question for load testing.',
    status: 'open',
    priority: 'normal',
    metadata: { scale_test: true },
  });
  const res = http.post(`${SUPABASE_URL}/rest/v1/rfis`, body, {
    headers: baseHeaders,
    tags: { op: 'rfi_create' },
  });
  check(
    res,
    { 'rfi_create status 201': (r: { status: number }) => r.status === 201 || r.status === 200 },
    { op: 'rfi_create' },
  );
}

function dailyLogCreate(orgId: string) {
  const body = JSON.stringify({
    organization_id: orgId,
    log_date: new Date().toISOString().slice(0, 10),
    weather: 'sunny',
    notes: `Scale-test daily log ${Date.now()}`,
    metadata: { scale_test: true },
  });
  const res = http.post(`${SUPABASE_URL}/rest/v1/daily_logs`, body, {
    headers: baseHeaders,
    tags: { op: 'daily_log_create' },
  });
  check(
    res,
    {
      'daily_log_create status 201': (r: { status: number }) =>
        r.status === 201 || r.status === 200,
    },
    { op: 'daily_log_create' },
  );
}

function aiCall(orgId: string) {
  const body = JSON.stringify({
    organization_id: orgId,
    prompt: 'Summarize the open RFIs for this project.',
    feature: 'scale_test',
    metadata: { scale_test: true },
  });
  const res = http.post(`${SUPABASE_URL}/functions/v1/iris-call`, body, {
    headers: baseHeaders,
    tags: { op: 'ai_call' },
  });
  check(
    res,
    { 'ai_call status 200': (r: { status: number }) => r.status === 200 },
    { op: 'ai_call' },
  );
}

function scheduleRead(orgId: string) {
  const res = http.get(
    `${SUPABASE_URL}/rest/v1/schedule_tasks?select=*&organization_id=eq.${orgId}&order=start_date.asc&limit=200`,
    { headers: baseHeaders, tags: { op: 'schedule_read' } },
  );
  check(
    res,
    { 'schedule_read status 200': (r: { status: number }) => r.status === 200 },
    { op: 'schedule_read' },
  );
}

function pdfExport(orgId: string) {
  const body = JSON.stringify({
    organization_id: orgId,
    document_type: 'rfi_log',
    metadata: { scale_test: true },
  });
  const res = http.post(`${SUPABASE_URL}/functions/v1/export-pdf`, body, {
    headers: baseHeaders,
    tags: { op: 'pdf_export' },
  });
  check(
    res,
    {
      'pdf_export status 200': (r: { status: number }) => r.status === 200 || r.status === 202,
    },
    { op: 'pdf_export' },
  );
}

// ---------------------------------------------------------------------------
// VU entry point
// ---------------------------------------------------------------------------
export default function () {
  const orgId = pickOrg();
  const op = pickOp();

  switch (op) {
    case 'rfi_read':
      rfiRead(orgId);
      break;
    case 'rfi_create':
      rfiCreate(orgId);
      break;
    case 'daily_log_create':
      dailyLogCreate(orgId);
      break;
    case 'ai_call':
      aiCall(orgId);
      break;
    case 'schedule_read':
      scheduleRead(orgId);
      break;
    case 'pdf_export':
      pdfExport(orgId);
      break;
  }

  sleep(SLEEP_BETWEEN_CALLS_SEC);
}
